services:
  lan-control-plane-server:
    build:
      context: ..
      dockerfile: server/Dockerfile
    container_name: lan-control-plane-server
    restart: unless-stopped
    env_file:
      - ./.env
    working_dir: /app/server
    volumes:
      - ./data:/app/server/data
    ports:
      - "8765:8000"
    networks:
      - private-net

  migrate:
    build:
      context: ..
      dockerfile: server/Dockerfile
    container_name: lan-control-plane-migrate
    env_file:
      - ./.env
    working_dir: /app/server
    volumes:
      - ./data:/app/server/data
      - ./alembic:/app/server/alembic
      - ./alembic.ini:/app/server/alembic.ini:ro
    command: >
      alembic upgrade head
    networks:
      - private-net
    profiles:
      - tools

  create-admin:
    build:
      context: ..
      dockerfile: server/Dockerfile
    container_name: lan-control-plane-create-admin
    env_file:
      - ./.env
    working_dir: /app/server
    volumes:
      - ./data:/app/server/data
      - ./scripts:/app/server/scripts
    command: >
      python /app/server/scripts/create_admin.py
    networks:
      - private-net
    profiles:
      - tools

  makemigrations:
    build:
      context: ..
      dockerfile: server/Dockerfile
    container_name: lan-control-plane-makemigrations
    env_file:
      - ./.env
    working_dir: /app/server
    volumes:
      - ./data:/app/server/data
      - ./src:/app/server/src
      - ../shared/src:/app/shared/src
      - ./alembic:/app/server/alembic
      - ./alembic.ini:/app/server/alembic.ini:ro
    command: >
      alembic revision --autogenerate -m "update schema"
    networks:
      - private-net
    profiles:
      - tools

networks:
  private-net:
    external: true
