services:
  lan-control-plane-web:
    build:
      context: ..
      dockerfile: web/Dockerfile
    container_name: lan-control-plane-web
    restart: unless-stopped
    env_file:
      - ./.env.production
    working_dir: /app
    command: npm run start
    networks:
      - public-net
      - private-net

networks:
  public-net:
    external: true
  private-net:
    external: true
